### ISSUE TITLE
Warning: Unused variable with child template

### ISSUE THREAD

**Issue by laurentmuller** [friendsoftwig/twigcs#121]
Say we have a base template:

```Twig
{# base_template.html.twig #}

{% set title = title|default('My Title') %}

{% block title %}
<p>{{ title }}</p>
{% endblock %}
```

And a child template:
```Twig
{# child_template.html.twig #}

{% extends 'base_template.html.twig' %}

{% set title = 'My other title' %}
```
When I run twigcs, an error is reported: 

`l.5 c.7 : WARNING Unused variable "title".`

It is possible to check if the given variable is used in the base template?

**Comment by OwlyCode** [comment]
At the moment twigcs doesn't handle multiple files. They are all linted as if they were alone. This would be a nice addition but it needs quite some work.

**Comment by valentin-harrang** [comment]
Hi @OwlyCode,

I have same issue with this code:

```
{% set pages = [
        {
            'title': 'Accueil',
            'url': '/'
        },
        {
            'title': page.header.menu,
            'url': null
        }
    ] %}

    {% include 'partials/_breadcrumb.html.twig' with {'pages': pages, 'backgroundImageUrl': url('theme://images/pattern/05.png')} %}
```

> WARNING Unused variable "pages".

Is there a clean method to no longer have this warning?

**Comment by OwlyCode** [comment]
Hi @ElGecko76! I checked your issue and could not reproduce it (on the v4-BETA branch). What version are you using?

**Comment by mgrsskls** [comment]
I can confirm the bug mentioned by @ElGecko76 is fixed in the v4 beta, but happens in v3.2.

**Comment by OwlyCode** [comment]
Thank you @mgrsskls. I won't fix on the v3.2 though because the code changed **a lot** (and the v3 approach is a dead end). You should use the v4 beta, it is way more stable than the v3 and includes all the latest bugfixes. Also it only breaks compatibility if you use a custom ruleset.

**Comment by jmsche** [comment]
I installed version 4.0.0 locally & have the same issue.

**Comment by Ciloe** [comment]
The development will be hard because it change the vision of twigcs. Today, we scan all files one by one and we work one it. For globalities, we will need to compute all files with childrens files and check if the variable is used or not. It will be hardest if in a template you have a variable, redeclare localy in a include and used in a third hierarchy template.

This breaking my mind xD 🤯 

If you have any ideas, that can be helpful !

**Comment by OwlyCode** [comment]
The real problem with cross-template checks is that you can have custom loaders with twig (FilesystemLoader, ArrayLoader, see: https://twig.symfony.com/doc/3.x/api.html#loaders). So you can't assume everything will be file based. But since the file-based configuration got released, it should be easier to allow loaders declaration inside them. This could open some solutions to this issue, but it needs a lot of work.

**Comment by mgrsskls** [comment]
Hey,

what about a case like this:

```
{% for entry in data %}
  {% include "@namespace/" ~ entry.something ~ "/" ~ entry.something ~ ".twig" with entry.data %}
{% endfor %}
```

twigcs@4 throws a warning here that `entry` is not used.

**Comment by adpeyre** [comment]
Is it possible to ignore this error while waiting?

**Comment by OwlyCode** [comment]
Sorry @adpeyre for taking ages to answer you. You can skip this with the following line: `{# twigcs use-var myVarName #}`. This comment counts as a usage and allows bypassing the problem until we come with a proper solution (it's a tough problem).

**Comment by OwlyCode** [comment]
As of 6.0.0 we added some kind of template resolution to allow usage detection across multiple templates. This is the best we can do right now to tackle this issue.
