### ISSUE TITLE
Example of using a custom ruleset

### ISSUE THREAD

**Issue by SeenNotHurd** [friendsoftwig/twigcs#70]
First of thanks for the work on this, it's the only stand alone twig CS I can find 🙏🏼

I am trying to implement my own ruleset as I really need to have a fix on the issue with the arrays (see #56 ) but I need that fixed before I can use this in production and on projects. 

Could you possibly give a detailed example of what needs to be done? I'm ok with Composer but certainly not an expert and I keep getting issues with the autoloader part. ( `Ruleset class must implement FriendsOfTwig\Twigcs\Ruleset\RulesetInterface` error all the time )

Thanks again for the awesome work!

**Comment by OwlyCode** [comment]
Hello and thank you for the kind words! It warms my heart to know that this tool is useful.

I'm afraid this issue can't be fixed using a custom ruleset without causing other problems elsewhere.

I got a lot of troubles in the past with the way spacing detection is handled and that's why a rewrite happened on the master branch. This problem should be fixed on it. It's still early but should be usable. It will lack customization though as I didn't write yet the documentation and some helper code.

**Comment by nicwortel** [comment]
Hi!

I just found this project this week and it works really nice for me!

I had some issues implementing a custom ruleset as well, that may or may not be related to the issues @SeenNotHurd ran into. They ended up having very little to do with autoloading, but instead with the fact that the backslashes in the fully qualified classname were removed by my shell. Because of that, even setting the ruleset to the official one resulted in an error:

> ```
> vendor/bin/twigcs --ruleset Allocine\Twigcs\Ruleset\Official
> 
> In LintCommand.php line 47:
>                                                                          
>   Ruleset class must implement Allocine\Twigcs\Ruleset\RulesetInterface  
>                                                                          
> 
> lint [-s|--severity SEVERITY] [-r|--reporter REPORTER] [--ruleset RULESET] [--] [<path>]
> ```
> 

Debugging showed that [at the point of checking whether `$ruleset` is a subclass of `RulesetInterface`](https://github.com/friendsoftwig/twigcs/blob/b2a38b996a9e7ac3b582eb116cd327229ddf759b/src/Console/LintCommand.php#L51-L53), the `$ruleset` variable contained "AllocineTwigcsRulesetOfficial" (all backslashes removed).

I'm not sure if this is a problem on other operating systems as well, but for me (Ubuntu 18.04) it is, so [the example in the readme](https://github.com/friendsoftwig/twigcs/blob/master/README.md#custom-coding-standard) is not working for me.

I fixed this by escaping the backslashes with more backslashes:

```
vendor/bin/twigcs --ruleset Allocine\\Twigcs\\Ruleset\\Official
```

although wrapping the ruleset in single quotes also seems to work:

```
vendor/bin/twigcs --ruleset 'Allocine\Twigcs\Ruleset\Official'
```

I think the readme should be updated to add double slashes / single quotes, or at least should warn about this (as I'm not sure if this is a problem for all operating systems / shells, or just for mine).

It may also be helpful to add a `class_exists()` before the `is_subclass_of()`, containing the value of `$ruleset` in the exception message for easier debugging.

@OwlyCode if you agree with my proposed changes, I'm willing to submit a pull request to change the readme and add a helpful exception message if the class cannot be found :wink: please let me know if you have a preference for either the single quotes or for escaping all backslashes.

**Comment by OwlyCode** [comment]
Hi @nicwortel and thank you for the detailed feedback, I would gladly merge a PR of that kind! I have no preference between backslashes and single quotes as it is a shell problem that each user might use the way he/her wants.

I'm on holiday at the moment and I might not review your PR until the beginning of september though. :surfing_man:

**Comment by OwlyCode** [comment]
I'm closing this as the related PR got merged. @SeenNotHurd are you still having troubles ?
